// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ExpenseTrackerAPI.Models
{
    public partial class Expenses
    {
        public int ExpenseId { get; set; }
        public decimal ExpenseValue { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public DateTime? Date { get; set; }
    }
}